[package]
name = "readonly-layer-files"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
libcnb.workspace = true

[dev-dependencies]
libcnb-test.workspace = true
