version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "rust"
      - "skip changelog"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
