[package]
name = "sbom"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
libcnb.workspace = true

[dev-dependencies]
libcnb-test.workspace = true
