[package]
name = "sbom"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
libcnb = { path = "../../libcnb" }

[dev-dependencies]
libcnb-test = { path = "../../libcnb-test" }
