[package]
name = "store"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
libcnb.workspace = true
toml.workspace = true

[dev-dependencies]
libcnb-test.workspace = true
