[package]
name = "libcnb-proc-macros"
version = "0.1.1"
edition = "2021"
rust-version = "1.58"
license = "BSD-3-Clause"
description = "Procedural macros used within libcnb.rs"
repository = "https://github.com/Malax/libcnb.rs/tree/main/libcnb-proc-macros"
documentation = "https://docs.rs/libcnb-proc-macros"
readme = "../README.md"
include = ["src/**/*", "../LICENSE", "../README.md"]

[lib]
proc-macro = true

[dependencies]
cargo_metadata = "0.14.2"
fancy-regex = "0.8.0"
quote = "1.0.15"
syn = { version = "1.0.86", features = ["full"] }
