[package]
name = "libcnb-proc-macros"
version = "0.10.0"
edition = "2021"
rust-version = "1.59"
license = "BSD-3-Clause"
description = "Procedural macros used within libcnb.rs"
repository = "https://github.com/heroku/libcnb.rs/tree/main/libcnb-proc-macros"
documentation = "https://docs.rs/libcnb-proc-macros"
readme = "README.md"
include = ["src/**/*", "../LICENSE", "README.md"]

[lib]
proc-macro = true

[dependencies]
cargo_metadata = "0.15.0"
fancy-regex = { version = "0.10.0", default-features = false }
quote = "1.0.20"
syn = { version = "1.0.98", features = ["full"] }
