[package]
name = "libcnb-proc-macros"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
license = "BSD-3-Clause"
description = "Procedural macros used within libcnb.rs"
repository = "https://github.com/Malax/libcnb.rs"
readme = "../README.md"
include = ["src/**/*", "../LICENSE", "../README.md"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.81", features = ["full"]}
quote = "1.0.10"
fancy-regex = "0.7.1"
