[package]
name = "libcnb-proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.81", features = ["full"]}
quote = "1.0.10"
fancy-regex = "0.7.1"
