name: Check Versions

on:
  # Only perform branch builds for `main`, to avoid duplicate builds on PRs.
  push:
    branches:
      - main
  pull_request:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that only one version is used across all workspace crates
        # Crates that are not published to any registry (i.e. examples, test buildpacks) will not be part of this check.
        run: |
          cargo metadata --no-deps --format-version 1 | jq -e '(.packages | map(select(.publish != false and .publish != [])) | group_by(.version) | length) == 1'
